/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "AudioRecording": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "AudioUploadBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "Credentials": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "MPMA-Web": {
      "type": "sst.aws.Remix"
      "url": string
    }
    "MyApi": {
      "name": string
      "type": "sst.aws.Function"
      "url": string
    }
    "Report": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Template": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
    "Users": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
